### PR TITLE
RESTWS-869: Refactor web-services module for quality assurance

### PR DESCRIPTION
**Pull request by kdaud**
## Description of what I changed

1. Removed unused imports
2. Organized imports based on OpenMRS import convention 
3.  Followed naming convention for constants. Refer to https://wiki.openmrs.org/display/docs/Java+Conventions#JavaConventions-NamingConventions
4. Renamed variables with better readable names
5. Removed unnecessary empty lines

## Issue I worked on

see https://issues.openmrs.org/browse/RESTWS-869

## Checklist: I completed these to help reviewers :)

- [ x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by kdaud** [comment]
@dkayiwa take a look at this guy to either pass him into master or throw some comments!

**Comment by dkayiwa** [comment]
@kdaud did you get a chance to look at this? https://opensource.com/article/18/6/anatomy-perfect-pull-request

**Comment by kdaud** [comment]
@dkayiwa have quickly skimmed through though had never read about the article. And thanks for sharing this wise advice

While going through the article, I noticed noticed down the things I didn't know and didn't put into consideration while creating this PR.

>  The pull request must have a maximum of 250 lines of change.
>A good pull request will be reviewed quickly
>It reduces bug introduction into codebase
>It facilitates new developers onboarding
>It does not block other developers
> It speeds up the code review process and consequently, product development

**Comment by dkayiwa** [comment]
Even if you exceeded the 250 lines of change, i would be happy with the pull request if it were in line with the rest of what is in that article.

**Comment by kdaud** [comment]
> i would be happy with the pull request if it were in line with the rest of what is in that article.

does this mean there is a way I can transform the commit to be valid one?

**Comment by dkayiwa** [comment]
All i wanted to say is that my major point in that article was not the 250 lines of change maximum. Even if you had 300 lines of change but which are in line with the rest of the points, i would merge it.

**Comment by kdaud** [comment]
Have re-read the article and found what I needed to address

> Describe what was changed in the pull request

Have added description of what has been changed [above](https://github.com/openmrs/openmrs-module-webservices.rest/pull/532#issue-785857617). Is there any point am missing out again?

**Comment by dkayiwa** [comment]
If that is the only other point that you saw in the article, then take a deep breath and carefully read it again. 😊

**Comment by kdaud** [comment]
After taking a cup of wora, I looked again on the article and I found this caption

> Just like classes and modules, pull requests should do only one thing

According to the caption above, it seems like there is less chance of making this commit valid!

**Comment by kdaud** [comment]
@dkayiwa am opting to sprint the ticket for the pull into sub tickets and contributors work on them!

**Comment by kdaud** [comment]
Hibernating this pull request based on the resolution [above](https://github.com/openmrs/openmrs-module-webservices.rest/pull/532#issuecomment-975470581)!

**Pull request closed without merging**
