### PR TITLE
Cleanup of warnings (unused imports, missing override annotations, deprecated Assert etc.)

### PR DESCRIPTION
**Pull request by lluismf**

### CODE REVIEW

**Comment by dkayiwa** [comment]
Thanks @lluismf :)

**Comment by k-joseph** [comment]
thanks @lluismf; does this have any impact on the previous issues raised by https://github.com/openmrs/openmrs-module-webservices.rest/pull/162 as mentioned on RESTWS-533 ticket @dkayiwa ?

**Comment by dkayiwa** [comment]
What impact?

On Tue, Oct 20, 2015 at 10:56 PM, k-joseph <notifications@github.com> wrote:

> thanks @lluismf <https://github.com/lluismf>; does this have any impact
> on the previous issues raised by #162
> <https://github.com/openmrs/openmrs-module-webservices.rest/pull/162> as
> mentioned on RESTWS-533 ticket @dkayiwa <https://github.com/dkayiwa> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openmrs/openmrs-module-webservices.rest/pull/164#issuecomment-149683074>
> .
>



-- 
If we keep uppermost in our minds the unkind and unjust acts of others, we
shall find it impossible to love them as Christ has loved us; but if our
thoughts dwell upon the wondrous love and pity of Christ for us, the same
spirit will flow out to others.

**Comment by k-joseph** [comment]
i would need to check out whether it positively affects the previously failing tests! any way, @rkorytkowski  seems to be taking RESTWS-533 on

**Comment by lluismf** [comment]
it should not have any effect, good or bad. There were +400 warnings, now just 140.

**Pull request merged**
