### PR TITLE
added ability to search encounters by either start date,end date, pat…

### PR DESCRIPTION
**Pull request by carapai**
…ient uuid or mixture of the above

### CODE REVIEW

**Comment by dkayiwa** [comment]
@carapai thanks for working on this. Can you add some unit tests? Can you also include the ticket number? Or did you take a look at https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by wluyima** [comment]
It would be nice to include unit tests for this addition

**Comment by wluyima** [comment]
Do you still have time to add unit tests for this @carapai ?

**Comment by dkayiwa** [comment]
@carapai remind me to reopen this when you get time to respond to the above.

**Pull request closed without merging**
