### PR TITLE
RESTWS-692 Support openmrs platform 2.2.x

### PR DESCRIPTION
**Pull request by JyothsnaAshok**
I've updated the resources which already supported version 2.1.x to support version 2.2.x 
see https://issues.openmrs.org/browse/RESTWS-692

### CODE REVIEW

**Comment by dkayiwa** [comment]
How about this class? GenericChildResource

**Comment by dkayiwa** [comment]
And a couple of classes in omod-1.9 are left out

**Comment by dkayiwa** [comment]
And other classes in omod-1.8 are left out

**Comment by JyothsnaAshok** [comment]
@dkayiwa I've made a few more chnanges. Please tell me if any other class is left out.

**Comment by dkayiwa** [comment]
You still have classes in omod-1.8 that are left out

**Pull request merged**
