### PR TITLE
Gsoc2015: Improving documentation generator

### PR DESCRIPTION
**Pull request by zak905**
Work done for GSOC 2015:

- Improving documentation generator 
- Integrating Swagger 
- Including search handlers

Project Wiki Page: https://wiki.openmrs.org/display/projects/REST+Documentation+Generator

Implementation notes on: https://drive.google.com/file/d/0B4Sn8X-cz8IzRVFUQUtEYlVKTlU/view?usp=sharing

### CODE REVIEW

**Comment by dkayiwa** [comment]
@zak905 do you still have some time to address these review comments?

**Comment by zak905** [comment]
@dkayiwa  I already did

**Comment by dkayiwa** [comment]
@zak905 this pull request has merge conflicts. Can you pull the latest changes from upstream?

**Comment by zak905** [comment]
@dkayiwa the branch is up to date now

**Comment by dkayiwa** [comment]
@zak905 do you mind squashing these commits into one?

**Comment by zak905** [comment]
@dkayiwa sure, why squashing all the 17 commits ?

2015-09-07 12:52 GMT+02:00 dkayiwa <notifications@github.com>:

> @zak905 <https://github.com/zak905> do you mind squashing these commits
> into one?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openmrs/openmrs-module-webservices.rest/pull/145#issuecomment-138268992>
> .
>



-- 
Zakaria Amine
Ingénieur d'études et de développement | Software Engineer
Tel: +33 616 47 86 95
Email: zakaria.amine88@gmail.com

**Comment by dkayiwa** [comment]
@zak905 it is part of our conventions as you can see at http://go.openmrs.org/pull-request-tips
One of the reasons is that it is easier to review when squashed. :)

**Comment by zak905** [comment]
@dkayiwa the commits are squashed

**Comment by dkayiwa** [comment]
@zak905 i still see a merge, can you pull the latest changes from upstream and try again?

**Comment by zak905** [comment]
@dkayiwa I don't understand. I squashed my commits, pulled from upstream, and then merged using git merge. It says that the branch is up-to-date with the base branch. what is wrong exactly ?

**Comment by dkayiwa** [comment]
@zak905 do you see the two lines on this page as listed below? I do not expect to see the merge.
Combination of all GSOC commits:
Merge upstream into branch gsoc2015 …

**Comment by zak905** [comment]
@dkayiwa I used git rebase instead of git merge, there is only one commit now.

**Comment by dkayiwa** [comment]
@zak905 other than the document link you provided above, do you have a link to the wiki project page?

**Comment by zak905** [comment]
@dkayiwa OK

**Comment by dkayiwa** [comment]
@wluyima and @rkorytkowski since you were the main and backup mentors for this project, do you have any general comments about this pull request?

**Comment by dkayiwa** [comment]
@zak905 did you really make changes to all these files? Or is the pull request having a problem with new line endings?

**Comment by wluyima** [comment]
For sure that pull request looks like it has line ending issues, you might
want to first fix that.

Wyclif

On Wed, Sep 16, 2015 at 9:36 AM, dkayiwa <notifications@github.com> wrote:

> @zak905 <https://github.com/zak905> did you really make changes to all
> these files? Or is the pull request having a problem with new line endings?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openmrs/openmrs-module-webservices.rest/pull/145#issuecomment-140744503>
> .
>



-- 
Wyclif Luyima
Regenstrief Institute Inc.

Confidentiality Notice: The contents of this message and any files
transmitted with it may contain confidential and/or privileged information
and are intended solely for the use of the named addressee(s).
Additionally, the information contained herein may have been disclosed to
you from medical records with confidentiality protected by federal and
state laws. Federal regulations and State laws prohibit you from making
further disclosure of such information without the specific written consent
of the person to whom the information pertains or as otherwise permitted by
such regulations. A general authorization for the release of medical or
other information is not sufficient for this purpose.

If you have received this message in error, please notify the sender by
return e-mail and delete the original message. Any retention, disclosure,
copying, distribution or use of this information by anyone other than the
intended recipient is strictly prohibited.

**Comment by zak905** [comment]
I have already tried before, but it does not seem to work properly. I followed what is described in: 

http://stackoverflow.com/questions/1510798/trying-to-fix-line-endings-with-git-filter-branch-but-having-no-luck/1511273#1511273

Any other suggestions ? 

@dkayiwa I can send you the list of files that have been created/modified

**Comment by lluismf** [comment]
I had this same problem for months (and some other people too). The solution IIRC was to remove the whole project from the workarea and start it again configuring GIT to not replace line endings. In the mailing list should be more info about it.

**Comment by zak905** [comment]
Thanks for the info. I have solved the issue by discarding the first three commits, and doing them manually. 

@dkayiwa I have created a new pull request : https://github.com/openmrs/openmrs-module-webservices.rest/pull/156

it seems like the issue is solved. We can close this one.

**Pull request closed without merging**
