### PR TITLE
RESTWS-925 Edited the nameTemplate

### PR DESCRIPTION
**Pull request by suubi-joshua**
## Description of what I changed
Update the  layout.name.format  Global Property to the custom template's codeName so that it is chosen as the active template.

## Issue I worked on

see https://issues.openmrs.org/browse/RESTWS-925

## Checklist: I completed these to help reviewers :)

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by brandones** [comment]
@dkayiwa I don't know what this change does, but it's supposed to fix https://openmrs.atlassian.net/browse/RESTWS-925 . Do you think this is the right approach? Obviously, if it is, we will need the PR cleaned up a lot, some demonstration that it actually works, etc. But would be nice to know if the solution makes sense in the first place.

**Comment by suubi-joshua** [comment]
@dkayiwa Is there a documentation on how I can test out my changes for the rest module locally. To see if what I have done produces the intended changes.

**Comment by dkayiwa** [comment]
@suubi-joshua did you try dropping the compiled module into the modules folder and restart openmrs?

**Comment by suubi-joshua** [comment]
> @suubi-joshua did you try dropping the compiled module into the modules folder and restart openmrs?

Yes I have done so using openmrs-core, the module builds successfully. 
But am still wondering how I can access the session end point data.

**Comment by dkayiwa** [comment]
By simply accessing the session end point url that i shared above.

**Comment by suubi-joshua** [comment]
> @suubi-joshua did you try dropping the compiled module into the modules folder and restart openmrs?

Yes I have done so using openmrs-core, the module builds successfully. 
But am still wondering how I can access the session end point data.

> By simply accessing the session end point url that i shared above.

Yes I have tried this but its giving me a 404 error. But am trying again to see if I did something wrong.

**Pull request closed without merging**
