### PR TITLE
Preethi, #RESTWS-507 | Named representation is not picked up correctl…

### PR DESCRIPTION
**Pull request by preethi29**
…y when there are more than one named representation in a resource

### CODE REVIEW

**Comment by sunbiz** [comment]
A unit test that fails before this fix is applied would be good to have as part of this ticket. @preethi29 , can you please add a unit test on any existing Resource that has a problem to this PR?

**Comment by preethi29** [comment]
@sunbiz Have added a test for ConceptResource, please check

**Comment by dkayiwa** [comment]
@sunbiz do you wanna give this a second review? :)

**Comment by sunbiz** [comment]
Thanks @dkayiwa for the ping... @preethi29 merged this. Thanks for the fix.

**Pull request merged**
