### PR TITLE
Gsoc2015: Improving documentation generator

### PR DESCRIPTION
**Pull request by zak905**
Work done for GSOC 2015:

Improving documentation generator
Integrating Swagger
Including search handlers
Project Wiki Page: https://wiki.openmrs.org/display/projects/REST+Documentation+Generator

Implementation notes on: https://drive.google.com/file/d/0B4Sn8X-cz8IzRVFUQUtEYlVKTlU/view?usp=sharing

### CODE REVIEW

**Comment by zak905** [comment]
@dkayiwa this should do it.

**Comment by dkayiwa** [comment]
@wluyima what do you think about this?

**Comment by lluismf** [comment]
Can't wait to see the swagger-generated documentation on the demo site !

**Comment by wluyima** [comment]
Do you mean what i think about the code in the PR? I reviewed this code as it got committed during the summer, so code wise it should be okay.

**Comment by lluismf** [comment]
So what are we waiting for?

**Comment by zak905** [comment]
Great.

**Pull request merged**
