### PR TITLE
RESTWS-812 Collection.isEmpty() should be used to test for emptiness

### PR DESCRIPTION
**Pull request by PranayChauhan2516**
## Issue I worked on

see https://issues.openmrs.org/browse/RESTWS-812

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by sacull** [comment]
1. Have you corrected all the cases you could?

2. Are you sure you added some tests? ;)
From PR description: 
image

3. You forgot to add a tag in the commit description.
image
Instead of `git commit -m "Some description"` it's better to do `git commit -m "RESTWS-812: Some description"`, where RESTWS-812 is the ticket number and the branch name.

4. This is the first time I see a SNYK error, but I don't have permission to see the details, so I don't know why this error popped up.

**Comment by PranayChauhan2516** [comment]
> 1\. Have you corrected all the cases you could?

Yes, I have corrected all the cases as mentioned.
 
 
> 2\. Are you sure you added some tests? ;)
>     From PR description:
>     image

I am sorry about this one, I misunderstood that statement.

> 3\. You forgot to add a tag in the commit description.
>     image

Can you guide me on how can  I change this one now?

> 4\. This is the first time I see a SNYK error, but I don't have permission to see the details, so I don't know why this error popped up.

I also don't have any idea about why this message popped up

**Comment by PranayChauhan2516** [comment]
> 3\. You forgot to add a tag in the commit description.

I have done git commit --amend and rebased and changed the previous commit with a new commit message. Why it is not visible in this pull request? It is visible in my forked repository only.

**Comment by sacull** [comment]
I just noticed that you are working on your master branch. This is a very bad practice. Please see [Pull Request Tips](https://wiki.openmrs.org/display/docs/Pull+Request+Tips), especially the part titled "Branch name == ticket name.".
We never work directly on the master branch, when we start working with a ticket, we create a branch called the ticket tag to make it easier to navigate the branches.

**Comment by PranayChauhan2516** [comment]
Can I close this pull request? And start again from the scratch.

**Comment by sacull** [comment]
Of course, just remember to update this information in your ticket comment.

**Pull request closed without merging**
