### PR TITLE
RESTWS-649 Update

### PR DESCRIPTION
**Pull request by gayanW**
Change to get original host and the port values of the running server.

Talk thread: https://talk.openmrs.org/t/how-to-get-server-details-from-httpservletrequest/13554

Issue: [RESTWS-649](https://issues.openmrs.org/browse/RESTWS-649)

### CODE REVIEW

**Comment by gayanW** [comment]
@dkayiwa 
There is a discussion going on about this in here:
https://talk.openmrs.org/t/how-to-get-server-details-from-httpservletrequest/13554

I'll ping you when this is ready to be merged.

**Comment by gayanW** [comment]
This is ready to be merged.
https://talk.openmrs.org/t/how-to-get-server-details-from-httpservletrequest/13554/16?u=gayanw

**Comment by dkayiwa** [comment]
@gayanW next time, can you use a more meaningful pull request title? ☺️

**Comment by gayanW** [comment]
@dkayiwa Sure :) But this is an update for the existing RESTWS-649 PR.

Will do 👍

**Comment by dkayiwa** [comment]
That does not still prevent you from giving it a meaningful title. 😊

**Pull request merged**
