### PR TITLE
RESTWS-483: REST API shouldn't depend on the attribute order in the JSON string which sends from the client side.

### PR DESCRIPTION
**Pull request by lluismf**
https://issues.openmrs.org/browse/RESTWS-483

### CODE REVIEW

**Comment by dkayiwa** [comment]
How about adding a simple unit test specifically for this change?

**Comment by lluismf** [comment]
ok I'll do it. Squashing commits as usual ?

**Comment by dkayiwa** [comment]
Sure!

On Thu, Oct 22, 2015 at 3:34 AM, Lluis Josep Martinez <
notifications@github.com> wrote:

> ok I'll do it. Squashing commits as usual ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openmrs/openmrs-module-webservices.rest/pull/165#issuecomment-150063428>
> .
>



-- 
If we keep uppermost in our minds the unkind and unjust acts of others, we
shall find it impossible to love them as Christ has loved us; but if our
thoughts dwell upon the wondrous love and pity of Christ for us, the same
spirit will flow out to others.

**Comment by lluismf** [comment]
Done!

**Pull request merged**
