### PR TITLE
RESTWS-756: Support openmrs platform 2.4.x

### PR DESCRIPTION
**Pull request by ODORA0**
**Issue worked on:** https://issues.openmrs.org/browse/RESTWS-756

### CODE REVIEW

**Comment by ODORA0** [comment]
@dkayiwa I think this is the last module, point out any I might have missed so I can do some justice to it :D

**Comment by dkayiwa** [comment]
Which modules have you done?

**Comment by dkayiwa** [comment]
@ODORA0 did you do for the emrapi module?

**Comment by ODORA0** [comment]
I did the webservices, reportingrest, IDGEN, Appointmentscheduling, AppFramework, and the coreapps which you haven't reviewed

**Comment by ODORA0** [comment]
Let me get underway for the emrapi module

**Pull request merged**
