### PR TITLE
RESTWS-608 Order resource missing property accessionNumber and schedu…

### PR DESCRIPTION
**Pull request by teleivo**
…ledDate

add missing property accessionNumber and scheduledDate to the OrderResource1_10

see https://issues.openmrs.org/browse/RESTWS-608

### CODE REVIEW

**Comment by dkayiwa** [comment]
@teleivo can you add these properties to the tests in OrderController1_10Test?

**Comment by teleivo** [comment]
@dkayiwa 

sure, is in https://github.com/openmrs/openmrs-module-webservices.rest/blob/master/omod-1.10/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_10/OrderController1_10Test.java#L116

good?

**Comment by dkayiwa** [comment]
@teleivo i see a number of tests that have several properties. So you could add to as many as you can.

**Comment by teleivo** [comment]
@dkayiwa added missing validateDefaultRepresentation/validateFullRepresentation to OrderResource1_10Test which now tests existence of all properties

**Pull request merged**
