### PR TITLE
RESTWS-509 Add SystemSettingsResource to get Global Properties

### PR DESCRIPTION
**Pull request by namratanehete**

### CODE REVIEW

**Comment by namratanehete** [comment]
I have added 1.12 version. Reused settingsProperty class as we discussed before. But following problem still exist.

As I wrote in ticket comments, setValue from GlobalProperty class, sets transient object whose value does not show up on the create response. i.e. when you post to create a new system setting. That is why controller unit test fails as mentioned above, but when you do get operation using uuid for newly created property, value is shown properly.
See here: https://issues.openmrs.org/browse/RESTWS-509?focusedCommentId=220355&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-220355

**Comment by namratanehete** [comment]
I have added tests shouldSaveSystemSettingWithCustomDatatype() and shouldSaveSystemSettingWithoutCustomDatatype().

**Comment by dkayiwa** [comment]
@namratanehete what IDE are you using? Are you editing from notepad? Your formatting is all messed up.

**Comment by namratanehete** [comment]
@dkayiwa I am using Netbeans IDE.

**Pull request merged**
