### PR TITLE
RESTWS-848:Check if Coveralls is working with REST Repo

### PR DESCRIPTION
**Pull request by sherrif10**
https://issues.openmrs.org/browse/RESTWS-848  cc @dkayiwa  @ibacher  @gracepotma
jacoco and coverals are configured in root pom pluginmanagement

### CODE REVIEW

**Comment by dkayiwa** [comment]
I quickly merged this to test this pull request: https://github.com/openmrs/openmrs-module-webservices.rest/pull/500
You can see that coveralls is none of the pull request checks.
Are you happy for me to revert this merge?

**Comment by dkayiwa** [comment]
@sherrif10 ^^

**Comment by sherrif10** [comment]
Sure @dkayiwa , we can revert, requesting to first test with the  https://coveralls.io/github/openmrs  and comfirm

**Comment by sherrif10** [comment]
Ohh sure , we can revert this and will add other configs in either maven.yml file or github actions

**Pull request merged**
