### PR TITLE
RESTWS-749: Add REST support for requesting and resetting password via email

### PR DESCRIPTION
**Pull request by fanyui**
RESTWS-749 Add REST support for requesting and resetting password via email

## Description of what I changed

Reset-Password-via-Email-Project Added REST support for password reset request via email and the actual resetting process.

## Issue I worked on

see https://issues.openmrs.org/browse/RESTWS-749
## Checklist: I completed these to help reviewers :)

- [ ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
Have you tried to run these changes in an instance of the OpenMRS platform and confirmed that all is well?

**Comment by fanyui** [comment]
@dkayiwa  Here is the new Pull request. i have just  after building, installed and tested my changes and its seems to work just fine. I will appreciate a review from anyone who takes it to review.

**Comment by dkayiwa** [comment]
Did you intentionally decide not to use the type of resources as already exist in this module?

**Comment by fanyui** [comment]
Yeah i compiled it ran all the test and installed it made a trigger to the endpoint and it worked with the following mail. sent
screen shot 2019-01-15 at 21 41 30

**Comment by fanyui** [comment]
It was actually not a resource an i thought since a controller could just do the work i decide to just use it.

**Comment by fanyui** [comment]
I also delibrated with this idea of using a controller with @wluyima  my gsoc mentor then.

**Comment by fanyui** [comment]
@dkayiwa  is there a better way i could have achieved this?, I will like to revisit and consider it.

**Comment by dkayiwa** [comment]
Can you give an example of the request that you made and its associated data?

**Comment by fanyui** [comment]
after installing the module and haven created a user with and associated email fanyuiharisu@gmail.com, i made a post request to the enpoint /openmrs/ws/rest/v1/passwordreset with body of request as {"usernameOrEmail":"fanyuiharisu@gmail.com"}
screen shot 2019-01-15 at 21 55 16

**Comment by fanyui** [comment]
this is after i set the mail configurations in my db as follows with mail.smtp.starttls.enable true mail.smtp_auth=true mail.transport_protocol=smtp mail.smtp_host=smtp.gmail.com

**Comment by dkayiwa** [comment]
Do we have all this documented somewhere like on the wiki?

**Comment by fanyui** [comment]
Well, This is not fully documented somewhere in the wiki but i will do it if the work is accepted and is considered valid

**Comment by dkayiwa** [comment]
Can you document it such that i use the documentation to test out these changes?

**Comment by fanyui** [comment]
Ok. I will get you the link to a wiki Here by tomorrow  so anyone who picks this up can review it easily

**Comment by dkayiwa** [comment]
That will be awesome! 👍

**Comment by fanyui** [comment]
@dkayiwa  here is the link to the wiki i created https://wiki.openmrs.org/pages/viewpage.action?pageId=216367317

**Comment by dkayiwa** [comment]
Thanks for doing this. Can you include a link to the ticket as required at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

Can you also squash the commits into one and include the ticket id in the commit message?

**Comment by fanyui** [comment]
Could the squashing be done on merge?. I see i will have to do a force update after squasing which will do away with the review history. As for the ticket link it was actually part of a project though i will reference the project on it.

**Comment by dkayiwa** [comment]
I can do that. But am scared of not having the ticket id in the commits. When bugs or issues are investigated, the ticket ids on commits help a great deal.

**Comment by fanyui** [comment]
i just updated the description of on the pull request

**Comment by dkayiwa** [comment]
But the commit message still do not have a ticket id

**Comment by fanyui** [comment]
As i said it wasn't really a ticket it was a project and thats jut part of the project. unless i have to create it as a ticket before referencing i just in the description reference the entire project which the part of it was already merged in core.

**Comment by dkayiwa** [comment]
Can you create a ticket for it?

**Comment by fanyui** [comment]
Ok

**Comment by fanyui** [comment]
issue link https://issues.openmrs.org/browse/RESTWS-749 needs assessment

**Comment by dkayiwa** [comment]
I have made it ready for work.

**Comment by dkayiwa** [comment]
Did you get a chance to look at this? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by fanyui** [comment]
@dkayiwa  Sorry for asking but i have taken a look and i seem not to be able to find what is lacking Except for the one commit which you will squash when merging. I also deleted related pull request wrt this issue.  may you point out what lacks in the pull request?

**Comment by dkayiwa** [comment]
Did you read about the JIRA work flow on that tips page?

**Comment by fanyui** [comment]
Thanks

**Comment by dkayiwa** [comment]
Have you included the ticket id in the commit message as advised at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by fanyui** [comment]
Yeah i did it already.

**Comment by dkayiwa** [comment]
Where? I see multiple commits in this pull request.

**Comment by fanyui** [comment]
Ohh We last agreed after your review it you will squash when merging to preserve the reviews you have been giving here. I will go ahead to squash them

**Comment by samuelmale** [comment]
@fanyui  can you include the Ticket Id in your commit message?

**Comment by fanyui** [comment]
@samuelmale  I have done the update.

**Comment by samuelmale** [comment]
Can you also rename your branch to be equal to the ticket Id?

**Comment by fanyui** [comment]
This has branch has been renamed to RESTWS-749 [here](https://github.com/openmrs/openmrs-module-webservices.rest/pull/383)

**Pull request closed without merging**
