### PR TITLE
RESTWS-517: Added state transition functionality in ProgramEnrollment…

### PR DESCRIPTION
**Pull request by preethi29**
… Resource

### CODE REVIEW

**Comment by preethi29** [comment]
Just added another commit. Adding a new PatientState to ProgramEnrollmentResource works fine. However, updates do not work. Have added a failing test to show the problem (ProgramEnrollmentController1_10Test.shouldUpdateExistingState()). 

Need advice. :)

**Comment by preethi29** [comment]
Should I create a new pull request squashing all those commits?

**Comment by dkayiwa** [comment]
@preethi29 you can just make all the changes you need, and squash all the commits into one.

**Comment by preethi29** [comment]
@dkayiwa Please review the change now

**Pull request merged**
