### PR TITLE
RESTWS-859: End point Obs create test

### PR DESCRIPTION
**Pull request by kdaud**
## Description of what I changed

Added end point obs create test

## Issue I worked on

see https://issues.openmrs.org/browse/RESTWS-858

## Checklist: I completed these to help reviewers :)

- [x ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
Are you sure that we do not already have tests for creating obs?

**Comment by kdaud** [comment]
> Are you sure that we do not already have tests for creating obs?

After going through the [ObsController1_9Test file](https://github.com/openmrs/openmrs-module-webservices.rest/blob/master/omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ObsController1_9Test.java) I realised we already have the tests for creating Obs.

@dkayiwa could it be a good idea to update the [Platform REST-WS endpoint tests spreadsheet](https://docs.google.com/spreadsheets/d/1vrVYIjVZqxzS2FHmD63KGV2wqvpJN-x-k77atS6TtIM/edit#gid=0) for the tests that are now pending otherwise the test in this PR is being tracked as uncovered!

**Comment by dkayiwa** [comment]
Update the first column with the link to the test/s.

**Comment by kdaud** [comment]
> Update the first column with the link to the test/s.

Have done the needful !!

**Comment by kdaud** [comment]
Am closing this commit PR since we already have tests for creating obs in [ObsController1_9Test ](https://github.com/openmrs/openmrs-module-webservices.rest/blob/master/omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/ObsController1_9Test.java) file.

**Pull request closed without merging**
