### PR TITLE
RESTWS-925: Session endpoint 'user.person.display' should respect the name template.

### PR DESCRIPTION
**Pull request by IamMujuziMoses**
## Issue I worked on

see https://issues.openmrs.org/browse/RESTWS-925

## Checklist: I completed these to help reviewers :)

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by IamMujuziMoses** [comment]
@brandones @dkayiwa @ibacher could you please review this PR, your feedback will be appreciated.

**Comment by dkayiwa** [comment]
@IamMujuziMoses is there a reason why you do not want this to be available for lower versions of the platform?

**Comment by IamMujuziMoses** [comment]
> @IamMujuziMoses is there a reason why you do not want this to be available for lower versions of the platform?

@dkayiwa in order for the session endpoint `user.person.display` to respect the `NameTemplate`, we need an updated version of `NameSupport` which is only available in `openmrs 2.7.0-SNAPSHOT`

**Comment by dkayiwa** [comment]
Platform 2.7.0 just added the ability to customise it via a global property. But the session end point should still respect even the default name template.

**Comment by IamMujuziMoses** [comment]
Ohh, okay, let me work on it🙂

**Comment by IamMujuziMoses** [comment]
@dkayiwa I have pushed an updated commit, please take a look.

**Comment by ibacher** [comment]
I'm closing this PR because, to the best of my knowledge, this feature is already implemented. [See the comment here](https://talk.openmrs.org/t/help-with-issue-restws-925-displaying-user-name-with-name-template/42458/2).

**Pull request closed without merging**
