### PR TITLE
RESTWS-509 Added SystemSettingsResource to get Global Properties

### PR DESCRIPTION
**Pull request by namratanehete**

### CODE REVIEW

**Comment by namratanehete** [comment]
Example of beautifying section as below:
Before beautifying: concept_map_type_management 
After: Concept Map Type Management
OR
Before: dashboard 
After: Dashboard

Example of beautifying name as below:
Before: encounters.maximumNumberToShow 
After: Encounters Maximum Number To Show
OR
Before: medicalRecordObservations 
After: Medical Record Observations

**Comment by dkayiwa** [comment]
@namratanehete do you mind quashing the commits into one?

**Comment by dkayiwa** [comment]
@namratanehete i still see more than one commit in this pull request. You need to squash them into one.

**Comment by dkayiwa** [comment]
@namratanehete did you also run mvn clean install after these changes to ensure that no test fails?

**Comment by namratanehete** [comment]
@dkayiwa As I wrote in ticket comments, setValue from GlobalProperty class, sets transient object whose value does not show up on the create response. i.e. when you post to create a new system setting. That is why controller unit test fails as mentioned above, but when you do get, using uuid for newly created property, value is shown properly.
See here: https://issues.openmrs.org/browse/RESTWS-509?focusedCommentId=220355&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-220355

**Comment by namratanehete** [comment]
I will make all the changes and send the pull request.

**Comment by namratanehete** [comment]
I have created new pull request because after pulling latest code from master, my pull request is showing other user's changes.

**Pull request closed without merging**
