### PR TITLE
RESTWS-799: Overriding methods should do more than simply call the sa…

### PR DESCRIPTION
**Pull request by kdaud**
## Issue I worked on

see https://issues.openmrs.org/browse/RESTWS-799

## Checklist: I completed these to help reviewers :)

- [ X] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [X ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [X ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ X] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [X ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by sacull** [comment]
When you close one PR and open a second one that solves the same problem, it is good to link them to each other, so that the person who will view it one day will know that the closed PR has its continuation in another.

**Comment by kdaud** [comment]
> When you close one PR and open a second one that solves the same problem, it is good to link them to each other, so that the person who will view it one day will know that the closed PR has its continuation in another.

The first one was not a PR as per say, it was a Draft

**Comment by sacull** [comment]
Sometimes it's good to share the knowledge of how you got here. And that's where it is. However, you will do as you like, because it's your PR. ;)

**Review by sacull — APPROVED** [review]
It's good for me. ;)

**Comment by sacull** [comment]
@kdaud I think you've mastered Jira and Github, so you can leave the intro tickets and look for something more difficult. ;)

**Comment by dkayiwa** [comment]
> @kdaud I think you've mastered Jira and Github, so you can leave the intro tickets and look for something more difficult. ;)

I totally agree 😊

**Comment by kdaud** [comment]
@dkayiwa  @sacull  Am looking for tickets that involve some thinking and probably reading or researching a bit here and there (tickets that suits my level as per say). Any pointer to such issues will be of help to advance to a more logical dev member for the organisation.

**Comment by dkayiwa** [comment]
@kdaud what do you think of this? https://issues.openmrs.org/browse/LUI-157

**Comment by kdaud** [comment]
> @kdaud what do you think of this? https://issues.openmrs.org/browse/LUI-157

Loool! Its worthy digesting. Am gonna dance around it until its resolved! Thanks @dkayiwa! You always inspire me in the tech error and desire to be like you some -> day. Some time am tempted to call you "a Rock Star"

**Comment by dkayiwa** [comment]
> desire to be like you some -> day

You aim too low! 😆

**Comment by kdaud** [comment]
@dkayiwa  @sacull  Am looking for tickets that involve some thinking and probably reading or researching a bit here and there (tickets that suits my level as per say). Any pointer to such issues will be of help to advance to a more logical dev member for the organisation. 

> > desire to be like you some -> day
> 
> You aim too low! laughing

Sure! You made me laugh off! Thinking through the puzzle before me!

**Pull request merged**
