### PR TITLE
RESTWS-872: Removed unused imports from files

### PR DESCRIPTION
**Pull request by Muta-Jonathan**
## Description of what I changed

Removed **unused imports** in all the module and removed **wildcards**

## Issue I worked on

see https://issues.openmrs.org/browse/RESTWS-872

### CODE REVIEW

**Comment by Muta-Jonathan** [comment]
cc @dkayiwa @kdaud

**Comment by kdaud** [comment]
@Muta-Jonathan did you take a look at these [imports](https://github.com/openmrs/openmrs-module-webservices.rest/blob/master/integration-tests/src/test/java/org/openmrs/module/webservices/rest/SessionIT.java#L14-L15)?

**Comment by Muta-Jonathan** [comment]
Let me fix it don't know how I missed them

**Comment by Muta-Jonathan** [comment]
cc @kdaud

**Review by kdaud — APPROVED** [review]
It's high time this pull request entered master!

cc: @dkayiwa

**Comment by kdaud** [comment]
> And then stop more experienced developers like @Muta-Jonathan from stealing them.

I totally agree @dkayiwa

**Comment by Muta-Jonathan** [comment]
😄

**Pull request merged**
