### PR TITLE
[RESTWS-693] Arrange resources alphanumerically in Swagger-Ui

### PR DESCRIPTION
**Pull request by tomekdo3**
#### Issue I worked on: https://issues.openmrs.org/browse/RESTWS-693

### CODE REVIEW

**Comment by collinsnji** [comment]
Thanks @tomekdo3 

@dkayiwa please review/merge this when you get the chance :)

**Comment by dkayiwa** [comment]
@gayanW do you approve this to be merged?
Can the upgrade be done in this pr?

**Comment by gayanW** [comment]
@dkayiwa yeah you can merge think. I think the upgrade is better done in a separate PR as it'll require more work.

**Comment by dkayiwa** [comment]
@gayanW are you creating the other ticket?

**Comment by gayanW** [comment]
@dkayiwa will do later :)

**Pull request merged**
