### PR TITLE
RESTWS-517 : Add program workflow state transition functionality in P…

### PR DESCRIPTION
**Pull request by shanmugam-radhakrishnan**
…rogramEnrollmentResource

### CODE REVIEW

**Comment by dkayiwa** [comment]
@shanmugam-radhakrishnan can you add some unit tests for this?

**Comment by shanmugam-radhakrishnan** [comment]
@dkayiwa Have added test. Please review.

**Comment by dkayiwa** [comment]
Can you squash these commits into one?

**Comment by preethi29** [comment]
@dkayiwa will raise a new pull request with squashed commits.

**Pull request closed without merging**
