### PR TITLE
updating next development version

### PR DESCRIPTION
**Pull request by HerbertYiga**
updating webservices module

### CODE REVIEW

**Comment by dkayiwa** [comment]
@HerbertYiga the next development version cannot be `2.32.0`

**Comment by HerbertYiga** [comment]
> the next development version cannot be `2.32.0`

@dkayiwa  sure,fixed

**Comment by dkayiwa** [comment]
@HerbertYiga can we improve the commit message?

**Comment by HerbertYiga** [comment]
> can we improve the commit message?

@dkayiwa  could it be better now

**Comment by dkayiwa** [comment]
next development version

**Comment by HerbertYiga** [comment]
> next development version

@dkayiwa  edited to  this

**Comment by dkayiwa** [comment]
@HerbertYiga do you need to mention `webservices` for an already webservices repository?

**Comment by HerbertYiga** [comment]
> do you need to mention `webservices` for an already webservices repository?

@dkayiwa fixed this

**Pull request merged**
