### PR TITLE
RESTWS-799: Overriding methods should do more than simply call the sa…

### PR DESCRIPTION
**Pull request by kdaud**
## Issue I worked on

see https://issues.openmrs.org/browse/RESTWS-

## Checklist: I completed these to help reviewers :)

- [ X] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [ X] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ X] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [X ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by kdaud** [comment]
Am working on this ticket But after meeting the ticket requirement, my changes seems to break the code when mvn clean install is  applied. Does it need to change some conditions in the test classes as well for those respective files!
cc: @sacull , @mozzy11 , @HerbertYiga , @ShekharReddy4

**Comment by HerbertYiga** [comment]
@kdaud  i see you have breaking tests in your ci,try adding a few changes build and see the out come,this will help you in trouble shooting the change that breaks things

**Comment by sacull** [comment]
@kdaud But why? Take advantage of the inheritance mechanism, instead of adding some implementations by force.

**Comment by kdaud** [comment]
> @kdaud But why? Use an inheritance mechanism, rather than adding some implementations by force.

Am working around to figure out the solution though not sure why am taking long

**Comment by sacull** [comment]
> Am working around to figure out the solution though not sure why am taking long

Look here: https://github.com/openmrs/openmrs-core/pull/3569 ;)

Instead of creating unnecessary implementations, you can use inheritance by removing these redundant methods in inheriting classes.

**Comment by kdaud** [comment]
> > Am working around to figure out the solution though not sure why am taking long
> 
> Look here: [openmrs/openmrs-core#3569](https://github.com/openmrs/openmrs-core/pull/3569) ;)
> 
> Instead of creating unnecessary implementations, you can use inheritance by removing these redundant methods in inheriting classes.

Oops! 
I get it the concept sir! Inheritance does it automatically without overriding the method in the subclasses! 
Thanks @sacull  for making me understand this concept now. Your are both a mentor and a coach!

**Pull request closed without merging**
