### PR TITLE
RESTWS-854: End point list encounter roles test

### PR DESCRIPTION
**Pull request by kdaud**
## Description of what I changed

Added end point list encounter roles test

## Issue I worked on

see https://issues.openmrs.org/browse/RESTWS-854

## Checklist: I completed these to help reviewers :)

- [x ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by kdaud** [comment]
This commit contains REST APT test for listing encounter roles. Here is the talk thread at https://talk.openmrs.org/t/test-coverage-for-our-rest-api/34671/17.
cc: @ibacher

**Comment by dkayiwa** [comment]
Are you intentionally duplicating this? https://github.com/openmrs/openmrs-module-webservices.rest/blob/master/omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/EncounterRoleController1_9Test.java#L68-L75

**Comment by dkayiwa** [comment]
@kdaud did you see the build failure? Do you even have to modify the existing test?

**Comment by dkayiwa** [comment]
How about the end point url in the spreadsheet?

**Comment by kdaud** [comment]
> How about the end point url in the spreadsheet?

Do you mean I update the first column with the link [here](https://github.com/openmrs/openmrs-module-webservices.rest/blob/master/omod-1.9/src/test/java/org/openmrs/module/webservices/rest/web/v1_0/controller/openmrs1_9/EncounterRoleController1_9Test.java#L68-L75) that redirects to the test implementation? Or you meant something else?

**Comment by dkayiwa** [comment]
Does the end point url do what that test is doing?

**Comment by dkayiwa** [comment]
@kdaud do you still need this?

**Comment by kdaud** [comment]
I have done the needful!

**Pull request closed without merging**
