### PR TITLE
RESTWS-511 : fix for broken build

### PR DESCRIPTION
**Pull request by r-nathan**
Pull request for build broken for RESTWS-511

### CODE REVIEW

**Comment by dkayiwa** [comment]
@r-nathan do you mind squashing these commits into one?

**Comment by r-nathan** [comment]
@dkayiwa Will do it now.

**Comment by r-nathan** [comment]
@dkayiwa Done the squash for commits.

**Comment by dkayiwa** [comment]
@r-nathan in the new resource test class, i would expect some assertions for the new properties you have just added. Did you just forget them? :)

**Comment by r-nathan** [comment]
@dkayiwa Thanks for the comments. I have added the assertions for the new properties to the test; amended to the previous commit. Please check. Thank you.

**Pull request merged**
