### PR TITLE
RESTWS-897: Fix the cohort members are not saving issue

### PR DESCRIPTION
**Pull request by anjula-sack**
## Description of what I changed

- Add the cohort members to the return data
- Fixed the cohort saving issue

## Issue I worked on

see https://issues.openmrs.org/browse/RESTWS-897

### Steps to reproduce:
* Cohort members are not receiving issue:
1. Create a cohort using the cohort API: `POST {{baseURL}}/openmrs/ws/rest/v1/cohort`
```
{
    "memberIds": [
        "9",
        "20"
    ],
    "description": "Male Patients years that are alive",
    "name": "male cohort"
}
```
2. Get the created cohort using:  `GET {{baseURL}}/openmrs/ws/rest/v1/cohort/{{uuid}}`
3. See `memberIds` are not there

<br>

* Cohort members are not saving issue

1. Create a cohort using the cohort API: `POST {{baseURL}}/openmrs/ws/rest/v1/cohort`
```
{
    "memberIds": [
        "9",
        "20"
    ],
    "description": "Male Patients years that are alive",
    "name": "male cohort"
}
```
2. See the cohort members table
3. The members are not saved.

## Checklist: I completed these to help reviewers :)

- [x] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by anjula-sack** [comment]
> @anjula-sack update the ticket description with as much details as you can. Link to error log, talk discussion thread if any, and anything else.

@dkayiwa I added steps to reproduce with the required payloads.

**Comment by ZacButko** [comment]
This makes sense to me. @dkayiwa what do you think?

**Comment by dkayiwa** [comment]
@anjula-sack i meant the JIRA ticket description.

**Comment by anjula-sack** [comment]
> @anjula-sack i meant the JIRA ticket description. It would also be great to include the error message you get on attempting to save.

Sure but It doesn't throw any errors. It just returns an empty array. @dkayiwa

**Comment by anjula-sack** [comment]
> @anjula-sack do we also have a talk discussion thread that led to this?

We have this [talk](https://talk.openmrs.org/t/cohort-builder-save-search-history-doesnt-work/33451/8?u=anjisvj) thread but I'm not sure whether this is related to the OpenMRS 1.0. Cohort builder. I found this when I was working on the 3.0 [Cohort Builder](https://talk.openmrs.org/t/gsoc-2022-redo-legacy-ui-cohort-builder-project-updates/36847/51?u=anjisvj). @dkayiwa

**Comment by dkayiwa** [comment]
@anjula-sack it is always a good practice for the JIRA ticket to include the talk thread link.

**Comment by anjula-sack** [comment]
> @anjula-sack it is always a good practice for the JIRA ticket to include the talk thread link that led to the creation of the ticket.

Done @dkayiwa

**Comment by dkayiwa** [comment]
@anjula-sack it would also be great to include some tests for this change.

**Comment by anjula-sack** [comment]
> @anjula-sack it would also be great to include some tests for this change.

This issue is no longer required because `memberIds` are deprecated as @ibacher informed. [Discussion](https://openmrs.slack.com/archives/CHP5QAE5R/p1661455484107969)

**Pull request closed without merging**
