### PR TITLE
TRUNK-4747-A

### PR DESCRIPTION
**Pull request by jdegraft**
Move allergyapi into core
- code changes, tested with core allergy ui

### CODE REVIEW

**Comment by jdegraft** [comment]
dkayiwa: here are the changes with no conflicts

**Comment by dkayiwa** [comment]
@jdegraft there are many commits in this pull request. Can you squash them into one as advised at http://go.openmrs.org/pull-request-tips

**Comment by jdegraft** [comment]
dkayiwa: The last commit is the only one, it is already squashed and has all the changes.

**Comment by dkayiwa** [comment]
@jdegraft squashing reduces them to one. Looks like you have not been lucky with squashing. So am closing such that you just create a new pull request.

**Pull request closed without merging**
