### PR TITLE
RESTWS-741: Remove 1.8 submodule

### PR DESCRIPTION
**Pull request by Ndacyayisenga-droid**
https://issues.openmrs.org/browse/RESTWS-741

RESTWS-741: Remove 1.8 submodule

Remove 1.8 submodule in openmrs-module-webservices.rest because its nolonger supported

cc @dkayiwa  @ibacher  @wluyima

### CODE REVIEW

**Comment by HerbertYiga** [comment]
thanks @Ndacyayisenga-droid   is this code available for version 1.9?

**Comment by Ndacyayisenga-droid** [comment]
> thanks @Ndacyayisenga-droid is this code available for version 1.9?

Thanks for the review @HerbertYiga .... Wont there be code repetition if i added everything to 1.9??

**Comment by HerbertYiga** [comment]
> > thanks @Ndacyayisenga-droid is this code available for version 1.9?
> 
> Thanks for the review @HerbertYiga .... Won't there be code repetition if i added everything to 1.9??

well i see,not sure whether we need to have any functionality from 1.8 to 1.9 cc @ibacher

**Comment by sherrif10** [comment]
cc @ibacher  , Well done @Ndacyayisenga-droid  , can you as well fix the merge conflicts.

**Comment by ibacher** [comment]
I'm pretty sure that making things work is going to require not just deleting code but moving things from the 1.8 submodule to the 1.9 submodule.

**Comment by sherrif10** [comment]
@Ndacyayisenga-droid  some conflicts to eat them up first.

**Comment by suubi-joshua** [comment]
I still see this as ticket on issues. Is it still available.

**Comment by suubi-joshua** [comment]
> I'm pretty sure that making things work is going to require not just deleting code but moving things from the 1.8 submodule to the 1.9 submodule.

I saw this issue is still open. I am trying to create classes in the 1.9 module that have some what the same code as that in the 1.8 module. 
Any advise on this

**Pull request closed without merging**
