### PR TITLE
Passwordresetrequest

### PR DESCRIPTION
**Pull request by fanyui**
## Issue I worked on

see https://issues.openmrs.org/browse/RESTWS-

## Checklist: I completed these to help reviewers :)

- [ ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by dkayiwa** [comment]
@fanyui did you see the merge conflicts?

**Comment by fanyui** [comment]
Hello @dkayiwa I have resolved the conflicts. Please have a look

**Comment by fanyui** [comment]
i reverted one of my commits and then did a force push to my branch and they suddenly appeared.

**Comment by dkayiwa** [comment]
Did you first pull the latest upstream changes before putting in yours? https://wiki.openmrs.org/display/docs/Using+Git

**Comment by fanyui** [comment]
i did not pull latest changes as this branch was created away from the master branch and was always in sync with my local since it was just managing my work. Pulling and rebasing from master would have meant i will be working and making pull request against master branch

**Comment by dkayiwa** [comment]
Can you create a pull request against the master branch?

**Comment by dkayiwa** [comment]
That will be awesome! 👍

**Comment by fanyui** [comment]
Closing this pull request because an alternate one has been made to the master branch here  https://github.com/openmrs/openmrs-module-webservices.rest/pull/377

**Pull request closed without merging**
