### PR TITLE
RESTWS-700 VisitTypeResource to process includeAll parameter

### PR DESCRIPTION
**Pull request by arunans23**
I worked on https://issues.openmrs.org/browse/RESTWS-700

### CODE REVIEW

**Comment by mks-d** [comment]
@dkayiwa , no unit tests required?

**Comment by dkayiwa** [comment]
@mks-d that is a very good one. @arunans23 i have reopened the ticket for some tests.

**Comment by mks-d** [comment]
@arunans23 look [here](https://github.com/openmrs/openmrs-core/blob/d1819f391dd3a64cff606ecceedefeef909b914a/api/src/test/resources/org/openmrs/include/standardTestDataset.xml#L433-L435), the standard test dataset holds three visit types, two active and one retired. That's enough to validate that all is well depending on whether `includeAll` is true or false.

**Comment by arunans23** [comment]
@mks-d @dkayiwa Thanks for pointing out. I'll try to write some unit tests with the suggested dataset

**Pull request merged**
