### PR TITLE
REST-793:remove empty statements

### PR DESCRIPTION
**Pull request by EllingtonK**
https://issues.openmrs.org/projects/RESTWS/issues/RESTWS-793

I removed both empty statements listed in the open issue.

## Checklist: I completed these to help reviewers :)

- [ ] My pull request only contains **ONE single commit**
(the number above, next to the 'Commits' tab is 1).

  No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by EllingtonK** [comment]
https://issues.openmrs.org/projects/RESTWS/issues/RESTWS-793

**Comment by sacull** [comment]
@EllingtonK Please fill in the description of the PR.

**Comment by HerbertYiga** [comment]
@EllingtonK as recommended here https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by EllingtonK** [comment]
Sorry, still learning.  I tried squashing my commits, but it still shows two, so I don't think it worked.  Can you squash them after you create the pull or it only updates the number of commits if you do it before you create the pull request?

**Comment by sacull** [comment]
I think you can leave two, but if you want to merge them into one, you can [squash](https://wiki.openmrs.org/display/docs/Git-Squashing+commits), and then push the changes with the --force option. Note, the --force option is not recommended as it deletes the history of any commits you changed in an earlier step.

**Pull request merged**
