### PR TITLE
RESTWS-753: Support openmrs platform 2.3.x

### PR DESCRIPTION
**Pull request by ODORA0**
Issue worked on: https://issues.openmrs.org/browse/RESTWS-753
work done: Added resources needed to support platform 2.3.* on resources that already support 2.2.*  in their supportedOpenmrsVersions

### CODE REVIEW

**Comment by mozzy11** [comment]
@ODORA0  have you seen the travis failure??

**Comment by mozzy11** [comment]
@ODORA0 , usualy first ensure that all tests run locally before you push

**Comment by mozzy11** [comment]
check here "[ERROR] /home/travis/build/openmrs/openmrs-module-webservices.rest/omod-2.2/src/main/java/org/openmrs/module/webservices/rest/web/v1_0/resource/openmrs2_2/DiagnosisResource2_2.java:[41,135] annotation values must be of the form 'name=value'"

**Comment by ODORA0** [comment]
@mozzy11 I don't understand the error because I made sure the resource was in the form `"2.3.*"` only after `"2.2.*"` so why would the Travis CI build refer to line 135 too

**Comment by dkayiwa** [comment]
@ODORA0 does the mvn clean install command fun successfully for you?

**Comment by ODORA0** [comment]
@dkayiwa No, I seem to have the same build failure in the same directory locally.

**Comment by ODORA0** [comment]
@dkayiwa  @mozzy11 I still have not been able to get the cause for the Travis build failure so as to have it a success. I actually thought removing the resource 2.3.x under DiagnosisResource2_2.java would solve but I think that's a wild catch for it, any help going through this?

**Comment by mozzy11** [comment]
@ODORA0  look at this . 
you did this `supportedOpenmrsVersions = "2.2.*", "2.3.*")`

when theyre multiple versions it should be  **supportedOpenmrsVersions = {"2.2.*", "2.3.*"})**

**Comment by ODORA0** [comment]
Ooh yes, thanks @mozzy11 let me change that.

**Comment by mozzy11** [comment]
ok this looks fine now.

**Comment by dkayiwa** [comment]
@ODORA0 how about UnrelatedGenericChildResource?

**Comment by ODORA0** [comment]
OK! Let me update that @dkayiwa

**Comment by dkayiwa** [comment]
I noticed a few more that you did not edit. Can you cross check and ensure that you have addressed it all?

**Comment by ODORA0** [comment]
@dkayiwa I haven't noticed those I haven't upgraded looked through most resources, could you point out some of them

**Comment by dkayiwa** [comment]
Which IDE are you using? Can you search for this '"2.2.*"' and tell me how many results that match?

**Comment by ODORA0** [comment]
Using eclipse, I have got a couple let me look through these for missing upgrades

**Comment by ODORA0** [comment]
I guess that's about it @dkayiwa

**Comment by dkayiwa** [comment]
How many more did you find?

**Comment by ODORA0** [comment]
Found 3 more un-upgraded resources

**Comment by dkayiwa** [comment]
Do you remember their names?

**Comment by ODORA0** [comment]
I don't get you when you say names but the resources not upgraded were in the  SearchConfig getSearchConfig() **under**  UserController1_8Test.java

**Comment by dkayiwa** [comment]
I mean names of classes/resources that you had forgotten to include.

**Comment by ODORA0** [comment]
The second edit were in the class `public static class UserSearchHandlerWithRequiredUsernameAndOptionalLocalesParams implements SearchHandler` 

 this `public static class UserSearchHandlerWithRequiredIdAndOptionalUsernameParams implements SearchHandler` 

and this `public static class UserSearchHandlerWithOptionalParam implements SearchHandler`
does that answer you because I don't remember the first edit

**Comment by dkayiwa** [comment]
@ODORA0 can you create a ticket and do the same for the reportingrest module? https://github.com/openmrs/openmrs-module-reportingrest

**Comment by ODORA0** [comment]
@dkayiwa  sure I will do

**Comment by ODORA0** [comment]
shall be done @dkayiwa

**Pull request merged**
